version: "3.8"

services:
  ms-sql-server:
    image: xmldockerid/ms-sql-server:latest
    restart: always
    volumes:
      - ms-sql-server-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  usermicroservice-api:
    image: xmldockerid/usermicroserviceapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.UserMicroservice
    depends_on:
      - ms-sql-server
    ports:
      - "8081:80"

  postmicroservice-api:
    image: xmldockerid/postmicroserviceapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.PostMicroservice
    depends_on:
      - ms-sql-server
    ports:
      - "44333:80"

  storymicroservice-api:
    image: xmldockerid/storymicroserviceapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.StoryMicroservice
    ports:
      - "8082:80"

  notificationmicroservice-api:
    image: xmldockerid/notificationmicroserviceapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.NotificationMicroservice
    depends_on:
      - ms-sql-server
    ports:
      - "44348:80"

  reportmicroservice-api:
    image: xmldockerid/reportmicroserviceapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.ReportMicroservice
    depends_on:
      - ms-sql-server
    ports:
      - "44382:80"

  campaignmicroservice-api:
    image: xmldockerid/campaignmicroserviceapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.CampaignMicroservice
    depends_on:
      - ms-sql-server
    ports:
      - "44381:80"

  agentapp-api:
    image: xmldockerid/agentappapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: ../../agentapp-backend/AgentAppSolution/Dockerfile
    ports:
      - "55744:80"

  apigateway:
    image: xmldockerid/apigateway:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.APIGateway
    ports:
      - "44355:80"

volumes:
  ms-sql-server-data:
  usermicroservice-api:
  postmicroservice-api:
  storymicroservice-api:
  notificationmicroservice-api:
  reportmicroservice-api:
  campaignmicroservice-api:
  agentapp-api:
