version: "3.8"

services:
  agentapp-api:
    image: xmldockerid/agentappapi:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "55744:80"

volumes:
  agentapp-api:
